[env:sensecap_indicator]
platform  = espressif32@6.5.0
board     = esp32s3box
framework = espidf

; 8 MB flash partitie-indeling (custom tabel, ESP-IDF)
board_build.partitions     = partitions.csv
board_upload.flash_size    = 8MB
board_upload.maximum_size  = 8388608

build_flags =
    -DBOARD_HAS_PSRAM
    -DAPP_VERSION=\"0.1.0\"
    -DLV_CONF_INCLUDE_SIMPLE
    ; lv_conf.h staat in include/ — ook nodig voor de lvgl-librarybuild
    -I include

lib_deps =
    lvgl/lvgl@~8.3.3
    bblanchon/ArduinoJson@^7.0.0
