[env:sensecap_indicator]
platform  = espressif32@6.5.0
board     = esp32s3box
framework = espidf

; 8 MB flash partitie-indeling
board_build.partitions     = default_8MB.csv
board_upload.flash_size    = 8MB
board_upload.maximum_size  = 8388608

; OPI PSRAM verplicht — LVGL framebuffer past niet in intern SRAM
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DAPP_VERSION=\"0.1.0\"
    -DLV_CONF_INCLUDE_SIMPLE
    -DARDUINO_USB_MODE=1
    ; Logging niveau (0=geen, 1=fout, 2=warn, 3=info, 4=debug)
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    lvgl/lvgl@^8.3.3
    bblanchon/ArduinoJson@^7.0.0
